parameters:
    vince_t.admin.twig.extension.class: VinceT\AdminBundle\Twig\Extension\VinceTAdminExtension
    vince_t.admin.theme.handler.class: VinceT\AdminBundle\Theme\ThemeHandler

services:
    vince_t.admin.twig.extension:
        class: %vince_t.admin.twig.extension.class%
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
    vince_t.admin.theme.handler:
        class: %vince_t.admin.theme.handler.class%
        arguments:
            - @service_container
