parameters:
#    vince_t_admin.example.class: VinceT\AdminBundle\Example

services:
#    vince_t_admin.example:
#        class: %vince_t_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
